### ISSUE TITLE
Build failed, gradle version 5.6.2

### ISSUE THREAD

**Issue by roman1v** [diffplug/durian-swt#6]
Could not resolve all files for configuration ':com.swt:compile'.
   > Could not find any matches for org.eclipse.platform:org.eclipse.swt.${osgi.platform}:[3.106.0,3.106.0] as no versions of org.eclipse.platform:org.eclipse.swt.${osgi.platform} are available.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.swt.${osgi.platform}/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.swt.${osgi.platform}/
     Required by:
         project :com.swttest > com.diffplug.durian:durian-swt:3.2.1 > org.eclipse.platform:org.eclipse.swt:3.106.0

**Comment by nedtwigg** [comment]
Did you close this because it's fixed now?

**Comment by roman1v** [comment]
It was a configuration issue, tnx
